name: Auto Version Bump

run-name: ${{ github.actor }} is running ${{ github.workflow }} on ${{ github.ref }}

on:
  push:
    branches:
      - dev

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver

      - name: Get last commit message
        id: get_commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV

      - name: Determine version increment
        id: version
        run: |
          current_version=$(cat version.txt)
          echo "Current version: $current_version"
          
          # Pass commit message to the script
          new_version=$(python3 ./scripts/increment_version.py "$current_version" "$COMMIT_MESSAGE")
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Bump version and commit
        run: |
          echo "$VERSION" > version.txt
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add version.txt
          git commit -m "Bump version to $VERSION"
          git push
