name: Auto Version Bump

run-name: ${{ github.actor }} is running ${{ github.workflow }} on ${{ github.ref }}

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'version.txt'

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver

      - name: Determine version increment
        id: version
        run: |          
          # run the script with the commit message
          new_version=$(python3 ./scripts/increment_version.py "${{ github.event.head_commit.message }}" | tail -1)
          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Bump version and commit
        run: |
          git add version.txt
          git commit -m "Bump version to $VERSION"
          git push https://x-access-token:${{ secrets.THE_GITHUB_PAT }}@github.com/${{ github.repository }}
