name: Auto Version Bump

run-name: ${{ github.actor }} is running ${{ github.workflow }} on ${{ github.ref }}

permissions:
  contents: write # required to push changes

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "version.txt"

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver

      - name: Bump version
        id: bump_version
        run: |
          # set environment variable for the script to use
          export THE_GITHUB_PAT=${{ secrets.THE_GITHUB_PAT }}
          export REPO=${{ github.repository }}
          export BRANCH=${{ github.ref }}
          python3 ./scripts/bump_version.py

